### ISSUE TITLE
Why does incorrect non-word take so long?

### ISSUE THREAD

**Issue by roughana** [a2-4am/untitled-word-game#3]
I entered DEARM as a guess and it took ~40 secs to respond that it was not a valid word.
This seems excessive. Are there really that many DExxx words?

**Comment by peterferrie** [comment]
It takes that long because the decompression is slow and the machine is slow.

The decompression is slow because it's hard.  It also checks the answer list before it checks the valid-words list.

Each "D" entry in the answer list is unpacked one at a time (we are running in only 16kb, after all) until we reach "DE" words.  Then each "DE" word is unpacked one at a time until we reach "DEA" words, and then each "DEA" word is unpacked one at a time ... until we run out of words.

If we don't find a match, then we do the same for the valid-words list.

So, we end up unpacking over 60 words before failing to find a match.

The upcoming ProDOS version doesn't use compression. It's faster.  Until then, perhaps run it under acceleration.
